import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Footer from "@/components/sections/Footer";
import NavigationBar from "@/components/layout/navigation/NavigationBar";
import Footer from "@/components/layout/footer/Footer";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Provider } from 'react-redux';
import store from "@/store/cartStore";
import { Providers } from "./Providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Providers>
      <NavigationBar/>
      <EdgeStoreProvider>{children}</EdgeStoreProvider>
      <Footer/>
      </Providers>
      <Toaster />
      </body>
    </html>
  );
}
