import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/layout/navigation/NavigationBar";
import Footer from "@/components/layout/footer/Footer";
import { Providers } from "./Providers";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import ClientChunkReload from "@/components/helper/ClientChunkReload";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ Fetch session server-side
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <NavigationBar /> {/* session now hydrated on first render */}
          {children}
          <Footer />
        </Providers>
        <Toaster />
        <ClientChunkReload />
      </body>
    </html>
  );
}
